#services:
#  mysql:
#    image: mysql:9.1
#    ports:
#      - "3306:3306"
#    environment:
#      - MYSQL_ROOT_PASSWORD=
#      - MYSQL_ALLOW_EMPTY_PASSWORD=true
#      - MYSQL_USER=petclinic
#      - MYSQL_PASSWORD=petclinic
#      - MYSQL_DATABASE=petclinic
#    volumes:
#      - "./conf.d:/etc/mysql/conf.d:ro"
#  postgres:
#    image: postgres:17.0
#    ports:
#      - "5432:5432"
#    environment:
#      - POSTGRES_PASSWORD=petclinic
#      - POSTGRES_USER=petclinic
#      - POSTGRES_DB=petclinic
services:
  server:
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_URL=jdbc:postgresql://db:5432/petclinic
  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_PASSWORD=petclinic
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "petclinic"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data: